# Generated by Django 5.0.6 on 2024-06-25 11:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorialescontenido',
            name='imagen',
        ),
        migrations.AddField(
            model_name='tutorialescontenido',
            name='recurso_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tutorialescontenido',
            name='descripcion',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
