# Generated by Django 5.0.6 on 2024-06-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_remove_tutorialescontenido_imagen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialescontenido',
            name='descripcion',
            field=models.TextField(),
        ),
    ]
