# Generated by Django 5.0.6 on 2024-06-24 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=200)),
                ('cuit', models.CharField(max_length=13)),
                ('domiciliocliente', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nrocompulsa', models.CharField(max_length=20)),
                ('afiliado', models.CharField(max_length=200)),
                ('domicilioafiliado', models.CharField(max_length=300)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oc.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('detalle', models.CharField(max_length=200)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orden_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='oc.ordencompra')),
            ],
        ),
    ]
