# Generated by Django 5.0.6 on 2024-06-24 22:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0002_ordencompra_entrega_unica_ordencompra_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
