# Generated by Django 5.0.6 on 2024-06-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0003_ordencompra_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha',
            field=models.DateField(),
        ),
    ]
