# Generated by Django 5.0.6 on 2024-11-02 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0004_alter_ordencompra_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('extracted_data', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cliente',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
