# Generated by Django 5.0.6 on 2024-11-10 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0006_ordencompra_cantidad_ordencompra_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='ordencompra',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='detalle',
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='importe_total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
