# Generated by Django 5.0.6 on 2024-11-10 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0007_remove_ordencompra_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfdocument',
            name='orden_compra',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='oc.ordencompra'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='nrocompulsa',
            field=models.CharField(blank=True, default='0000-0000', max_length=20, null=True),
        ),
    ]
