# Generated by Django 5.0.6 on 2024-11-10 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0009_alter_pdfdocument_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
