# Generated by Django 5.0.6 on 2024-11-10 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0011_pdfdocument'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PDFDocument',
        ),
    ]
