# Generated by Django 5.0.6 on 2024-11-10 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0012_delete_pdfdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='pdf',
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pdfs/')),
                ('extracted_data', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('orden_compra', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='oc.ordencompra')),
            ],
        ),
    ]
