# Generated by Django 5.0.6 on 2024-11-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oc', '0013_remove_ordencompra_pdf_pdfdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='orden_compra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='oc.ordencompra'),
        ),
    ]
